base: &base

  # Model config
  embed_dim: 384
  depth: 12
  dropout: 0.0
  patch_size: 8

  # Training config
  img_size: [360, 720]
  dt: 1 
  global_batch_size: 16 # number of samples per training batch
  num_epochs: 25
  amp_mode: none
  enable_fused: False
  enable_jit: False
  expdir: '/logs'
  lr_schedule: 'cosine'
  lr: 5E-4
  warmup: 0

  # Data
  data_loader_config: 'pytorch'
  num_data_workers: 0 # number of dataloader worker threads per proc
  n_in_channels: 20
  n_out_channels: 20
  train_data_path:   '/data/train'
  valid_data_path:   '/data/valid'
  inf_data_path:     '/data/test'
  time_means_path:   '/data/stats/time_means.npy'
  global_means_path: '/data/stats/global_means.npy'
  global_stds_path:  '/data/stats/global_stds.npy'
  limit_nsamples: None
  limit_nsamples_val: None

short: &short
  <<: *base
  limit_nsamples: 512
  limit_nsamples_val: 128
  num_epochs: 4

# Short config with full optimizations
short_opt:
  <<: *short
  data_loader_config: 'dali'
  num_data_workers: 8
  amp_mode: fp16

