base: &base

  # Model config
  embed_dim: 384
  depth: 12
  dropout: 0.0
  patch_size: 8
  num_heads: 8

  # Training config
  img_size: [360, 720]
  dt: 1 
  global_batch_size: 16 # number of samples per training batch
  num_iters: 60000
  amp_mode: none
  enable_fused: False
  enable_jit: False
  expdir: '/logs'
  lr_schedule: 'cosine'
  lr: 5E-4
  warmup: 0
  optimizer: 'Adam'

  # Data
  data_loader_config: 'pytorch'
  num_data_workers: 0 # number of dataloader worker threads per proc
  n_in_channels: 20
  n_out_channels: 20
  train_data_path:   '/data/train'
  valid_data_path:   '/data/valid'
  inf_data_path:     '/data/test'
  time_means_path:   '/data/stats/time_means.npy'
  global_means_path: '/data/stats/global_means.npy'
  global_stds_path:  '/data/stats/global_stds.npy'
  limit_nsamples: None
  limit_nsamples_val: None

short: &short
  <<: *base
  limit_nsamples: 512
  limit_nsamples_val: 128
  num_iters: 128

short_opt:
  <<: *short
  data_loader_config: 'dali'
  num_data_workers: 8
  amp_mode: bf16

opt: &opt
  <<: *base
  data_loader_config: 'dali'
  num_data_workers: 8
  amp_mode: bf16
  num_iters: 30000


# ----- Data parallel scaling configs


bs16_opt:
  <<: *opt
  global_batch_size: 16
  lr: 5e-4

bs32_opt:
  <<: *opt
  global_batch_size: 32
  lr: 7.07e-4

bs64_opt:
  <<: *opt
  global_batch_size: 64
  lr: 1e-3

bs128_opt:
  <<: *opt
  global_batch_size: 128
  lr: 1.41e-3

bs256_opt:
  <<: *opt
  global_batch_size: 256
  lr: 2e-3

bs512_opt:
  <<: *opt
  global_batch_size: 512
  lr: 2.83e-3

bs1024_opt:
  <<: *opt
  global_batch_size: 1024
  lr: 4e-3

bs2048_opt:
  <<: *opt
  global_batch_size: 2048
  lr: 5.66e-3

